apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: newrelic
rules:
- apiGroups: [""]
  resources:
  - "nodes"
  - "nodes/metrics"
  - "nodes/stats"
  - "nodes/proxy"
  - "pods"
  - "secrets"
  - "services"
  verbs: ["get", "list"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
